---
- name: Install required softwares on Amazon Linux
  hosts: localhost
  become: yes             
  tasks:
    - name: Update package cache
      ansible.builtin.yum:
        name: '*'
        state: latest
      become: yes

    - name: Install multiple packages using yum
      ansible.builtin.yum:
       name: "{{ item }}"
       state: present
      with_items:
        - python3-devel
        - python3
        - python3-pip
        - python3-devel
    - name: Install nginx
      ansible.builtin.command:
        cmd: amazon-linux-extras install nginx1 -y
    - name: Install the 'Development tools' package group
      ansible.builtin.yum:
        name: "@Development tools"
        state: present

    - name: Install required python modules
      ansible.builtin.pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      with_items:
        - wheel
        - uwsgi
        - boto
        - boto3
        - botocore
    - name: Start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
      become: yes
